greedy:
	clear
	g++ -std=c++11 greedy.cpp -o greedy.out
	./greedy.out < candy.txt 

itr:
	clear
	g++ -std=c++11 iterative.cpp -o itr.out
	./itr.out

exh:
	clear
	g++ -std=c++11 exhaustive.cpp -o exh.out
	./exh.out

all:
	clear
	g++ -std=c++11 greedy.cpp -o greedy.out
	./greedy.out < candy.txt 
	g++ -std=c++11 iterative.cpp -o itr.out
	./itr.out
	g++ -std=c++11 exhaustive.cpp -o exh.out
	./exh.out
